### ISSUE TITLE
There should be a "sort by date" option

### ISSUE THREAD

**Issue by sebbacon** [ClaudioMendoncaDesign/open-gazettes-interface#12]
This is a "should have" in the requirements, but I'd make it near the top of the "should haves", so it's quite likely to make the final cut. 

So we need to support it in the design.

**Comment by claudioccm** [comment]
I guess the options for the "sort by"menu will be pulled from rails. So the
list of options there right now is just for mock-up purposes. James, let me
know if I'm wrong.

**Comment by jpmckinney** [comment]
**Update:** Sorry, I read "filter by date". Claudio: Where is the "sort by" menu?

**Comment by claudioccm** [comment]
There isn't "Sort by" UI element. I will create one soon. Can you list for me all options we should have there? This wat I will make right on the first time.
