### ISSUE TITLE
Result text overflows card when heading is too long

### ISSUE THREAD

**Issue by sebbacon** [ClaudioMendoncaDesign/open-gazettes-interface#13]
![screenshot from 2016-02-25 07 51 10](https://cloud.githubusercontent.com/assets/211271/13313291/bd503dee-db94-11e5-9b34-24f09ee7649a.png)

**Comment by sebbacon** [comment]
Here's another example. It looks like it might overflow more than by the extra height of the header.

![overlap](https://cloud.githubusercontent.com/assets/211271/13313425/a7df0926-db95-11e5-809a-1a74c8ec0492.png)

**Comment by claudioccm** [comment]
this will be taken care by truncating the description text. I don'y know
how James wants to truncate it, but I see 4 possible ways of doing this: by
JS, by Ruby, by Nunjucks/Liquid or by CSS. James, please let me know if you
need me to do this.

**Comment by jpmckinney** [comment]
I can do it. Those two overflow because the title is too long on one and because the other is rendering line breaks.

**Comment by jpmckinney** [comment]
Done (in next deploy).
