### ISSUE TITLE
Vertical alignment of tagline on search page

### ISSUE THREAD

**Issue by jpmckinney** [ClaudioMendoncaDesign/open-gazettes-interface#14]
A one-line tagline doesn't look as good as a two-line tagline on the search page.

http://claudiomendoncadesign.github.io/open-gazettes-interface/public/search.html

**Comment by claudioccm** [comment]
I check that, in a couple of days.

All good on the surgery, at home resting/recovering. I should be back on
business pretty quick

**Comment by jpmckinney** [comment]
Happy to hear! Take it easy :)

**Comment by claudioccm** [comment]
This will be the official tagline?
"Bringing transparency to official public notices"

**Comment by jpmckinney** [comment]
It's the best we have so far!
