### ISSUE TITLE
Use case illustrations

### ISSUE THREAD

**Issue by jpmckinney** [ClaudioMendoncaDesign/open-gazettes-interface#20]
Logging as an issue to have everything represented here.

**Comment by jpmckinney** [comment]
@claudioccm I think we can continue making more illustrations. Can you specify which use cases you'll make illustrations for?

**Comment by claudioccm** [comment]
I want to make those 3D renders for each of the 5 use cases. That's why I want to keep doing them. I will implement them in my version here, so people can see it.

**Comment by claudioccm** [comment]
![use-case-3](https://cloud.githubusercontent.com/assets/1649373/14386317/348b4e5e-fd72-11e5-9377-7467f80969e7.png)
![use-case-4](https://cloud.githubusercontent.com/assets/1649373/14386316/348b2b2c-fd72-11e5-8085-68b7c6dfdc53.png)
![use-case-5](https://cloud.githubusercontent.com/assets/1649373/14386318/348bbb14-fd72-11e5-81a3-5b84f2758543.png)
