### ISSUE TITLE
Try a version of gazette page with company details to the right of the notice

### ISSUE THREAD

**Issue by jpmckinney** [ClaudioMendoncaDesign/open-gazettes-interface#21]
This may require moving other elements (the buttons, mainly).

**Comment by claudioccm** [comment]
@jpmckinney: I created an alternative layout for this. Please let me know which one is the winner, so I can get rid of the other one. :)

**Comment by jpmckinney** [comment]
I have the go-ahead for us to keep iterating on the new layout.

**Comment by jpmckinney** [comment]
Some notices are extremely long (megabytes of text). Where should we put the buttons so that people see them without scrolling forever?

**Comment by jpmckinney** [comment]
Implemented, e.g. http://opengazettes.com/gazette_notices/361728763
