### ISSUE TITLE
Styles needed for active filter links

### ISSUE THREAD

**Issue by jpmckinney** [ClaudioMendoncaDesign/open-gazettes-interface#22]
I added a link around each filter's text. The link color blends into the background color.

http://claudiomendoncadesign.github.io/open-gazettes-interface/public/search.html

**Comment by claudioccm** [comment]
@jpmckinney, I'm wondering why we need that `<a>` there. 
All we need there is to hook the `active-filters__handle` class in the JS, right?

In fact, I'd even use something like `js-active-filters-trigger` so you can keep the JS related classes scoped. 

Is there another reason we have that anchor tag there?

**Comment by jpmckinney** [comment]
I have a real `href` value there in the app. I won't have any JS.

**Comment by claudioccm** [comment]
ok, makes sense.
