### ISSUE TITLE
Alert messages

### ISSUE THREAD

**Issue by jpmckinney** [ClaudioMendoncaDesign/open-gazettes-interface#23]
Related to login, we need to display error messages.

**Comment by claudioccm** [comment]
let me create a full login page. Seems logical, right?

**Comment by jpmckinney** [comment]
We are using OAuth2, so users will click a "Login with OpenCorporates" button (or something like that), and then they will be redirected to OpenCorporates to login.

**Comment by claudioccm** [comment]
ok, so we don't need the login page?

**Comment by jpmckinney** [comment]
Yeah, no need.

**Comment by claudioccm** [comment]
if you need other options for the alert messages, let me know. We can have several of them. It's really easy to add new ones
