### ISSUE TITLE
Should the account circle have a dropdown?

### ISSUE THREAD

**Issue by jpmckinney** [ClaudioMendoncaDesign/open-gazettes-interface#25]
Just wondering what the behavior should be. What should people see when logged in versus logged out? What would prompt people to click that icon to create an account?

**Comment by claudioccm** [comment]
I don't know. What do you think you will need for that dropdown?

**Comment by jpmckinney** [comment]
I don't know. Right now I think adding a "Login / Register" and "Logout" label would make things clearer.

**Comment by claudioccm** [comment]
do we have an online version with the whole ruby thing working? I'm trying to understand this better.

**Comment by jpmckinney** [comment]
Soon!

**Comment by claudioccm** [comment]
You need this urgently?

**Comment by jpmckinney** [comment]
No, you will be able to see a Ruby thing working soon :)

**Comment by claudioccm** [comment]
haha, ok. Awesome!

**Comment by jpmckinney** [comment]
Deployed so that you can see http://alpha.opengazettes.com
