### ISSUE TITLE
"Flag as private" button

### ISSUE THREAD

**Issue by jpmckinney** [ClaudioMendoncaDesign/open-gazettes-interface#27]
(We may change the button's label.)

Clicking the button would present the user with a form where they can enter their email address and a message explaining why they believe the notice contains personal information and should therefore be hidden from unregistered users according to the [privacy policy](https://docs.google.com/document/d/1Lt_nlmA7mllRY6GoL6q_eDxSwjHnMahFVPnEhHTWwJE/edit#heading=h.gnushaek0bkd).

The form could be on a new page, the same page – I'm open to anything.

**Comment by claudioccm** [comment]
I think this would be better if done with a modal window.
I will create the modal component, and some form elements for this.

Sounds good?

**Comment by jpmckinney** [comment]
Sounds good!

**Comment by claudioccm** [comment]
added the modal on the gazette-page.html file. it is fully functional. I'm sure you will want to make it a macro, but I didn't know the best way to do that. Let me know if you need anything else on this.
