### ISSUE TITLE
Sign-in iterations

### ISSUE THREAD

**Issue by jpmckinney** [ClaudioMendoncaDesign/open-gazettes-interface#31]
I got some feedback:

> Couldn't immediately see where to login, and then didn't know if I was already logged in

One of the targets required by the funder is to reach a certain number of registered users, so I think the login option needs to be much more prominent.

**Comment by jpmckinney** [comment]
cc @claudioccm

**Comment by claudioccm** [comment]
I used the "call to action" section on the homepage, to highlight the register information. I think we need a better text for that. Maybe more information about what is included in the "registered" version. I'd like to have some content for that. It would make things easier and more concrete.

@jpmckinney: From what we discussed over the phone, that is what I could come up with. Let me know how we should move this forward.

**Comment by jpmckinney** [comment]
The team has agreed to count users in Google Analytics instead of counting them via registrations, so it's no longer critical to strongly encourage user accounts. So, status quo is fine.
