### ISSUE TITLE
Search results list view element overlap

### ISSUE THREAD

**Issue by jpmckinney** [ClaudioMendoncaDesign/open-gazettes-interface#35]
The category overlaps and hides part of the notice's text.

![screen shot 2016-04-26 at 2 19 39 pm](https://cloud.githubusercontent.com/assets/26463/14829540/fc2cd14e-0bb9-11e6-9bf3-cb8b05afa19e.png)

**Comment by jpmckinney** [comment]
Also, if there's no title, the text goes under the flag: http://opengazettes.com/search?utf8=%E2%9C%93&q=barclays&jurisdiction_code[]=gb&jurisdiction_code[]=&publication_title[]=&date_published__gte=&date_published__lte=&per_page=10

**Comment by jpmckinney** [comment]
![screen shot 2016-04-28 at 09 00 18](https://cloud.githubusercontent.com/assets/26463/14884459/5dddb07c-0d1b-11e6-9f04-d11e10d8edda.png)

**Comment by jpmckinney** [comment]
The second comment is still an issue, e.g. flag covers text on http://opengazettes.com/search?utf8=%E2%9C%93&q=barclays&jurisdiction_code[]=gb&jurisdiction_code[]=&publication_title[]=&date_published__gte=&date_published__lte=&per_page=10

**Comment by claudioccm** [comment]
Let me know if this is fine. I just pushed a fix for it. @jpmckinney

**Comment by jpmckinney** [comment]
Works, thanks!
