### ISSUE TITLE
Mobile: Can't dismiss menu

### ISSUE THREAD

**Issue by jpmckinney** [ClaudioMendoncaDesign/open-gazettes-interface#36]
If you open the menu, you can't dismiss it without clicking a menu option

**Comment by claudioccm** [comment]
This is happening because you don't have the `overlay` element in your version. 
@gmattar, can you point the exact place for @jpmckinney to copy?

**Comment by gmattar** [comment]
Line 91 in `_base.html`: `<div class="overlay js-overlay"></div>`
https://github.com/ClaudioMendoncaDesign/open-gazettes-interface/blob/gh-pages/source/templates/_base.html#L91

**Comment by jpmckinney** [comment]
Thanks!
