### ISSUE TITLE
If the notices aren't the same length, the notices stack badly

### ISSUE THREAD

**Issue by jpmckinney** [ClaudioMendoncaDesign/open-gazettes-interface#6]
See http://claudiomendoncadesign.github.io/open-gazettes-interface/public/

**Comment by claudioccm** [comment]
I fixed this, but it will require that we set a maximum number of characters to the description text. 

There is another option, that would require some JS calculate the heights on the fly. This is the thing, from the foundation library (http://foundation.zurb.com/sites/docs/equalizer.html)

**Comment by jpmckinney** [comment]
We need to truncate the text anyway (the text can be megabytes long), so that's fine with me.

**Comment by claudioccm** [comment]
Also added styling so the boxes can be anchor tags, to link directly to the notices.
