### ISSUE TITLE
Typed text in the search box is the same color as background

### ISSUE THREAD

**Issue by jpmckinney** [ClaudioMendoncaDesign/open-gazettes-interface#9]
http://claudiomendoncadesign.github.io/open-gazettes-interface/public/

**Comment by sebbacon** [comment]
Not for me (Chromium 37)

**Comment by jpmckinney** [comment]
Firefox (latest stable)

**Comment by claudioccm** [comment]
this is the bug: http://stackoverflow.com/questions/12971300/box-sizing-on-inputs-in-firefox-hides-text

Checking it right now
